# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
  
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [ '8.0.x', '9.0.x' ]

    steps:
    - name: Print Context
      if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        echo "Repo: ${{ github.repository }} event: ${{ github.event_name }} pusher: ${{ github.event.pusher.name }}"
        if [ "${{ github.event_name }}" = "push" ]; then
          echo "Author: ${{ github.event.head_commit.author.name }}"
          echo "Added: ${{ toJson(github.event.head_commit.added) }}"
          echo "Commit: ${{ github.event.head_commit.message }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"
        fi

            
                  
    
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}

        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      id: build
      run: dotnet build --no-restore
      
    - name: Test
      if: ${{ steps.build.conclusion == 'success' }}
      run: dotnet test --no-build --verbosity normal
